stages:
- build-docker
- release
- deploy

variables:
  DOCKER_REGISTRY: registry.gitlab.com
  DOCKER_DRIVER: overlay
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

build-docker: 
  image: docker:latest
  stage: build-docker  
  services:
  - docker:dind
  before_script:
  - docker info
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $DOCKER_REGISTRY
  script:  
  - docker build -t $CONTAINER_TEST_IMAGE .
  - docker push $CONTAINER_TEST_IMAGE
  
release-image:
  image: docker:latest
  stage: release
  services:
  - docker:dind
  before_script:
  - docker info
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $DOCKER_REGISTRY
  script:
  - docker pull $CONTAINER_TEST_IMAGE
  - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
  - docker push $CONTAINER_RELEASE_IMAGE
  only:
  - master

deploy:
  image: alpine
  stage: deploy
  before_script:
  - apk add --no-cache curl
  script:  
  - curl -H "X-Token:$DEPLOY_TOKEN" https://api.enbiso.com/v1/webhook/hooks/redeploy?app=carsalesama
  only:
  - master
